//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
let sumOfEvenValued = 0;
function fibonacci(n){
        if(Number.isInteger(n)){
            if(n == 0){
                return 1;
            }
            else if(n == 1){
                return 2
            }
            else if(n > 1){
                return fibonacci(n-2) + fibonacci(n-1)
            }
}    
}

console.log(fibonacci(5))
let x = 0
    while(fibonacci(x) < 4000000){
    x++;
        if(fibonacci(x) % 2 == 0){
            sumOfEvenValued += fibonacci(x) 
        }
}

console.log(sumOfEvenValued)